### ISSUE TITLE
Mapping between non odin resources

### ISSUE THREAD

**Issue by jokiefer** [python-odin/odin#137]
I want to map two different datastructures by using this package.

For example one resource is a django model and one is a simple python object. The datastructure of the two classes differs. So i wrote a mapper:

```python
from odin.mapping import Mapping, map_field
from ows_lib.xml_mapper.capabilities.wms.wms130 import \
    WebMapService as XmlWebMapService
from registry.models.service import WebMapService


class WebMapServiceToXml(Mapping):
    from_obj = WebMapService
    to_obj = XmlWebMapService

    @map_field(from_field='title', to_field='service_metadata.title')
    def title(self, value):
        return value
```

To update the existing xml from the django object i tried:

```python
    @property
    def updated_capabilitites(self) -> XmlObject:
        """Returns the current version of the capabilities document.

            The values from the database overwrites the values inside the xml document.
        """
        xml_object: OGCServiceMixin = self.xml_backup
        from registry.mapping.service import WebMapServiceToXml

        mapper = WebMapServiceToXml(source_obj=self, )
        mapper.update(destination_obj=xml_object)

        return xml_object
```

This results in an exception:

```traceback
Traceback (most recent call last):
django-tests_1         |   File "/opt/mrmap/tests/django/registry/models/tests_document.py", line 40, in test_current_capabilities
django-tests_1         |     capabilities: XmlWebMapService = wms.updated_capabilitites
django-tests_1         |   File "/opt/mrmap/registry/models/document.py", line 108, in updated_capabilitites
django-tests_1         |     from registry.mapping.service import WebMapServiceToXml
django-tests_1         |   File "/opt/mrmap/registry/mapping/service.py", line 7, in <module>
django-tests_1         |     class WebMapServiceToXml(Mapping):
django-tests_1         |   File "/opt/venv/lib/python3.10/site-packages/odin/mapping/__init__.py", line 184, in __new__
django-tests_1         |     raise MappingSetupError(
django-tests_1         | odin.exceptions.MappingSetupError: `from_obj` <class 'registry.models.service.WebMapService'> does not have an attribute resolver defined.

```

What does dies exception means to me?
Do i need to make clear that any field of the both resources has type hints?

**Comment by timsavage** [comment]
Mappers need to resolve what fields are available to be mapped, this is done by registering a FieldResolver against the type (or super type) to be mapped. The development release has [updated documentation covering this](https://odin.readthedocs.io/en/development/ref/mapping/classes.html#mapping-other-types).

There is also an example of how to do this with Django models here: https://odin.readthedocs.io/en/development/integration/django/index.html

**Comment by jokiefer** [comment]
seems like that the resolvers now works for the django models and my play python object with the following example:

```python
from django.db.models import Model
from odin import registration
from odin.mapping import FieldResolverBase
from odin.utils import getmeta
from ows_lib.xml_mapper.mixins import CustomXmlObject


class ModelFieldResolver(FieldResolverBase):
    """
    Field resolver for Django Models
    """

    def get_field_dict(self):
        meta = getmeta(self.obj)
        return {f.attname: f for f in meta.fields}


class XmlMapperFieldResolver(FieldResolverBase):
    """
    Field resolver for XML Objects
    """

    def get_field_dict(self):
        xml_obj = self.obj
        return {key: getattr(xml_obj, key) for key in filter(lambda key: not key.startswith('_'), xml_obj._fields.keys())}


registration.register_field_resolver(ModelFieldResolver, Model)
registration.register_field_resolver(XmlMapperFieldResolver, CustomXmlObject)
```

But now the custom field mapping crashes:
```traceback
Traceback (most recent call last):
django-tests_1         |   File "/opt/mrmap/tests/django/registry/models/tests_document.py", line 40, in test_current_capabilities
django-tests_1         |     capabilities: XmlWebMapService = wms.updated_capabilitites
django-tests_1         |   File "/opt/mrmap/registry/models/document.py", line 110, in updated_capabilitites
django-tests_1         |     from registry.mapping.service import WebMapServiceToXml
django-tests_1         |   File "/opt/mrmap/registry/mapping/service.py", line 7, in <module>
django-tests_1         |     class WebMapServiceToXml(Mapping):
django-tests_1         |   File "/opt/venv/lib/python3.10/site-packages/odin/mapping/__init__.py", line 303, in __new__
django-tests_1         |     mapping_rule = attr_mapping_to_mapping_rule(
django-tests_1         |   File "/opt/venv/lib/python3.10/site-packages/odin/mapping/__init__.py", line 253, in attr_mapping_to_mapping_rule
django-tests_1         |     raise MappingSetupError(
django-tests_1         | odin.exceptions.MappingSetupError: Field `service_metadata.title` of custom mapping `<function WebMapServiceToXml.title at 0x7fdee0c6d360>` not found on to object.

```

How can is map sub hierarchical properties like `service_metadata.title`  in the `WebMapServiceToXml` class above?

**Comment by timsavage** [comment]
It might help if you could provide the data structures (or a basic outline) so I can understand the structures you are attempting to map.

The mappers are largely to map to an object rather than into an attribute on a nested object. Rather than mapping to a model containing the object to be updated, could you just map directly to that object? eg provide `model.service_metadata` as the update destination.

**Comment by jokiefer** [comment]
I want to map and update from my django db model [WebMapService](https://github.com/mrmap-community/mrmap/blob/0a3b54f7f893513ffb66e5b32885923b2d4d23f6/backend/registry/models/service.py#L121) to the xml representing [WebMapService](https://github.com/mrmap-community/mrmap/blob/0a3b54f7f893513ffb66e5b32885923b2d4d23f6/backend/ows_lib/xml_mapper/capabilities/wms/wms130.py#L150) object for example. For some reasons the xml object structure differs from the orm structure. 

The ORM model inheritance the service metadata, for example `title` so that this attribute is directly owned by the orm model. The xml object does not directly ownes the title attribute. It is an attribute of an child object called [service_metadata](https://github.com/mrmap-community/mrmap/blob/0a3b54f7f893513ffb66e5b32885923b2d4d23f6/backend/ows_lib/xml_mapper/capabilities/wms/wms130.py#L158)

**Comment by jokiefer** [comment]
In my pov i determined that what iam thinking about to do with your lib is not possible for now.

For example the [update routine](https://github.com/python-odin/odin/blob/695fbe5844778cb26b928eb43fecfb816cbdba0f/src/odin/mapping/__init__.py#L695) is a simple straightforward looping over the applied mapping rules on a single destination object. So those rules are always on the same hierarchy level.

There should be something like a `deep_update`
```python
    def update(
        self,
        destination_obj,
        ignore_fields=None,
        fields=None,
        ignore_not_provided=False,
    ):
        """
        Update an existing object with fields from the provided source object.

        :param destination_obj: The existing destination object.
        :param ignore_fields: A list of fields that should be ignored eg ID fields
        :param fields: Collection of fields that should be mapped.
        :param ignore_not_provided: Ignore field values that are `NotDefined`

        """
        ignore_fields = ignore_fields or []

        for mapping_rule in self._mapping_rules:
            for name, value in self._apply_rule(mapping_rule).items():
                if not (
                    (name in ignore_fields)
                    or (fields and name not in fields)
                    or (ignore_not_provided and value is NotProvided)
                ):
                    if '.' in name:
                        # deep updating attribute of sub object
                        sub_object_name, sub_attribute_name = name.split('.')
                        if not isinstance(_name, str):
                            raise NotImplementedError("can't update sub-sub attributes")
                        sub_object = getattr(destination_obj, sub_object_name)
                        setattr(sub_object, sub_attribute_name, value)
                    else:
                        setattr(destination_obj, name, value)
```

**Comment by jokiefer** [comment]
> Typically to map into a sub-object a second mapper is used specifically for that type, a mapping rule can pass the value to another mapper to generate the new object.

Could you provide an example how i can do this?

**Comment by timsavage** [comment]
I'm simulating your existing object with Odin Resources. For a single field this is overkill, but if you need to update a lot of values the mappings become much easier.

```python
import odin


class DBModel(odin.AnnotatedResource):
    title: str


class WebServiceMetadata(odin.AnnotatedResource):
    title: str


class WebServiceModel(odin.AnnotatedResource):
    service_metadata: WebServiceMetadata


class DBModelToWebServiceMetadata(odin.Mapping):
    from_obj = DBModel
    to_obj = WebServiceMetadata


class DBModelToWebServiceModel(odin.Mapping):
    from_obj = DBModel
    to_obj = WebServiceModel

    @odin.assign_field
    def service_metadata(self):
        return DBModelToWebServiceMetadata.apply(self.source)


# Using apply and generating a new instance
my_db_model = DBModel(title="This is the new title")
web_service_model = DBModelToWebServiceModel.apply(my_db_model)
print(f"Created with title: {web_service_model.service_metadata.title}")

# With update
my_web_service_model = WebServiceModel(
    service_metadata=WebServiceMetadata(title="Old Title")
)
DBModelToWebServiceMetadata(my_db_model).update(my_web_service_model.service_metadata)
print(web_service_model.service_metadata.title)
print(f"Updated title to: {my_web_service_model.service_metadata.title}")
```

**Comment by jokiefer** [comment]
thanks for the solution. I adapt it for my special use case like this:
```python
from copy import deepcopy

from odin.mapping import Mapping, assign_field
from ows_lib.xml_mapper.capabilities.wms.wms130 import \
    ServiceMetadata as XmlServiceMetadata
from ows_lib.xml_mapper.capabilities.wms.wms130 import \
    WebMapService as XmlWebMapService
from registry.models.service import WebMapService


class ServiceMetadataToXml(Mapping):
    from_obj = WebMapService
    to_obj = XmlServiceMetadata


class WebMapServiceToXml(Mapping):
    from_obj = WebMapService
    to_obj = XmlWebMapService

    def __init__(self, xml_root: XmlWebMapService, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.xml_root: WebMapService = xml_root

    @assign_field
    def service_metadata(self):
        """ Updating the service metadata field by using the concrete mapper and a deep copy of the old xml object

        .. note::
           Can't be handled by the apply function as predicted in https://github.com/python-odin/odin/issues/137#issuecomment-1408750868
           Cause the xml mapper objects only handles a subset of all xpaths which are present in a capabilities document (only database relevant fields), 
           the usage of apply will create a new fresh xml mapper object with just the xml structure of the concrete attributes which are handled by it. 
           So this will not represent the full valid xml structure of a valid capabilities document. So we need to update the existing xml objects. 

        .. note:: 
           Update routine from the odin package will only work if the object instances are not the same, 
           cause otherwise the setattr() will result in empty data. 
           Don't know why... 
           So it is necessary to do a deepcopy of the existing object first.
        """
        return ServiceMetadataToXml(source_obj=self.source).update(
            destination_obj=deepcopy(self.xml_root.service_metadata))


```


For me this is the easiest way to update all fields downward the full complex structure of a complete ogc capabilitites document from the db models. Tanks.
