### ISSUE TITLE
How to use mapping_factory with custom base mapping and dynamic to_obj ressources

### ISSUE THREAD

**Issue by jokiefer** [python-odin/odin#139]
In my use case i use different `to_obj` resources which are calculated on runtime.

I tried it with the `mapping_factory` like this:

### base_mapping definitions

```python

class LayerToXml(Mapping):
    from_obj = Layer
    # to_obj = ? unknown on class definition, known on runtime

    def update(self, destination_obj, *args, **kwargs):
        self.destionation_obj = destination_obj
        return super().update(destination_obj=self.destionation_obj, *args, **kwargs)

    @assign_field(to_list=True)
    def keywords(self):
        return [str(keyword) for keyword in self.source.keywords.all()]

    @assign_field(to_list=True)
    def styles(self):
        # FIXME: find style and update instead of creating them with apply
        xml_style_mapper_cls = getattr(import_module(
            get_import_path_for_xml_mapper(self.destionation_obj.serializeDocument())), "Style")
        stye_mapper = forward_mapping_factory(
            from_obj=Style, to_obj=xml_style_mapper_cls)
        _styles = []
        for style in self.source.styles.all():
            _styles.append(stye_mapper.apply(source_obj=style))
        return _styles


class WebMapServiceToXml(OgcServiceToXmlMixin, Mapping):
    from_obj = WebMapService
    # to_obj = ? unknown on class definition, known on runtime

    def update(self, *args, **kwargs):
        updated_service = super().update(*args, **kwargs)
        self._update_layers()
        return updated_service

    def _update_layers(self):
        for layer in self.source.layers.filter(is_active=True):
            xml_layer_mapper_cls = getattr(import_module(get_import_path_for_xml_mapper(
                self.destionation_obj.serializeDocument())), "Layer")
            layer_mapper = forward_mapping_factory(
                from_obj=layer, to_obj=xml_layer_mapper_cls, base_mapping=LayerToXml)
            layer_mapper.update(destination_obj=self.destination_obj.get_layer_by_identifier(
                identifier=layer.identifier))

        for layer in self.source.layers.filter(is_active=False):
            xml_layer = self.destination_obj.get_layer_by_identifier(
                identifier=layer.identifier)
            if xml_layer:
                del xml_layer

```

### utility function to build a mapper on the fly

```python
def get_mapper_for_service(service) -> Mapping:
    from registry.models.service import WebMapService

    if isinstance(service, WebMapService):
        if service.version == "1.3.0":
        # the service version is 1.3.0, so we need to import the resource class from the wms130 package
            from ows_lib.xml_mapper.capabilities.wms.wms130 import \
                WebMapService as XmlWebMapService
            from registry.mapping.capabilities.wms.wms130 import \
                WebMapServiceToXml
            return forward_mapping_factory(from_obj=WebMapService, to_obj=XmlWebMapService, base_mapping=WebMapServiceToXml)


```

### traceback
This results in the following exception:

```traceback
Traceback (most recent call last):
django-tests_1         |   File "/opt/mrmap/tests/django/registry/models/tests_document.py", line 52, in test_current_capabilities
django-tests_1         |     capabilities: XmlWebMapService = self.wms.updated_capabilitites
django-tests_1         |   File "/opt/mrmap/registry/models/document.py", line 109, in updated_capabilitites
django-tests_1         |     mapper: Mapping = get_mapper_for_service(self)
django-tests_1         |   File "/opt/mrmap/registry/mapping/capabilities/utils.py", line 21, in get_mapper_for_service
django-tests_1         |     from registry.mapping.capabilities.wms.wms130 import \
django-tests_1         |   File "/opt/mrmap/registry/mapping/capabilities/wms/wms130.py", line 11, in <module>
django-tests_1         |     class MetadataUrlToXml(Mapping):
django-tests_1         |   File "/opt/venv/lib/python3.10/site-packages/odin/mapping/__init__.py", line 170, in __new__
django-tests_1         |     raise MappingSetupError("`to_obj` is not defined.")
django-tests_1         | odin.exceptions.MappingSetupError: `to_obj` is not defined.
```

It seams to be that the to_obj attr is needed to be set, but i will set it by the factory on runtime. How can i do this?

**Comment by jokiefer** [comment]
I fixed the issue above by inherite from `MappingBase` and `metaclass=MappingMeta` like:
```python
class WebMapServiceToXml(MappingBase, metaclass=MappingMeta):


```

The factory methods generates me the mapper classes dynamically now. But  decorated mapping rules like `@assign_field` is no longer attached to the mapping rules of this mappers. So the `keywords` and `styles` field from the example above wont be  taken into account from the `update()` routine which iterates over the `self._mapping_rules`. The `keywords` and `styles` are not part of the mapping rule set.

Any ideas on this?

**Comment by jokiefer** [comment]
Seems to be that custom mapping is only possible on classes which inherit from `Mapping` class.



```python

class MappingMeta(type):
    """
    Metaclass for all Mappings
    """

    def __new__(mcs, name, bases, attrs):
        super_new = super(MappingMeta, mcs).__new__

        # attrs will never be empty for classes declared in the standard way
        # (ie. with the `class` keyword). This is quite robust.
        if name == "NewBase" and attrs == {}:
            return super_new(mcs, name, bases, attrs)

        parents = [
            b
            for b in bases
            if isinstance(b, MappingMeta)
            and not (b.__name__ == "NewBase" and b.__mro__ == (b, MappingBase, object))
        ]

        
        if not parents:
            # If this isn't a subclass of Mapping, don't do anything special.
            return super_new(mcs, name, bases, attrs)

```

The parent lookup is the reason why no custom mapping will be attached.


So back to my initial question. Is there a solution add custom mapping on the fly with the factory?

**Comment by jokiefer** [comment]
I've done it by passing the mappings to the factory like:

```python
class WebMapServiceToXml(MappingBase, metaclass=MappingMeta):

    def keywords(self):
        return [str(keyword) for keyword in self.source.keywords.all()]

    def update(self, destination_obj, *args, **kwargs):
        self._destination_obj = deepcopy(destination_obj)
        updated_service = super().update(
            destination_obj=self._destination_obj, *args, **kwargs)
        self._update_operation_urls(updated_service=updated_service)
        self._update_layers()
        return updated_service

    def _update_operation_urls(self, updated_service):
        operation_urls = []
        for operation_url in self.source.operation_urls.all():
            operation_urls.append(
                OperationUrl(
                    method=operation_url.method,
                    url=operation_url.url,
                    operation=operation_url.operation,
                    mime_types=[str(mime_type) for mime_type in operation_url.mime_types.all()]))
        updated_service.operation_urls = operation_urls

    def _update_layers(self):
        mappings = []
        mappings.append(assign(to_field="remote_metadata",
                        action=LayerToXml.remote_metadata, to_list=True))
        mappings.append(
            assign(to_field="styles", action=LayerToXml.styles, to_list=True))
        mappings.append(assign(to_field="keywords",
                        action=LayerToXml.keywords, to_list=True))

        for layer in self.source.layers.filter(is_active=True):
            xml_layer_mapper_cls = getattr(import_module(get_import_path_for_xml_mapper(
                self._destination_obj.serializeDocument())), "Layer")
            layer_mapper_cls = forward_mapping_factory(
                from_obj=Layer, to_obj=xml_layer_mapper_cls, base_mapping=LayerToXml, mappings=mappings)
            layer_mapper = layer_mapper_cls(source_obj=layer)
            layer_mapper.update(destination_obj=self._destination_obj.get_layer_by_identifier(
                identifier=layer.identifier))

        for layer in self.source.layers.filter(is_active=False):
            xml_layer = self._destination_obj.get_layer_by_identifier(
                identifier=layer.identifier)
            if xml_layer:
                del xml_layer

```

For now everything seems to be working. 
In my POV the documentation should be approved by providing some examples to use all the functionality.
